// script.js (最終・決定版 - プレミアム分析拡充 & 品質統一)

// 1. データの定義
// =================================
// 全16タイプの詳細データ（前回と同じ、完全版です）
const mbtiData = {
    "INTJ": { alias: "建築家", title: "INTJ (建築家型)", tagline: "独創的な戦略で、あらゆる物事を改善する完璧主義者", description: "想像力豊かで、常に戦略的な思考を張り巡らせています。あらゆる物事に対して計画を立て、その知性と自信で目標を達成します。知識を渇望し、非効率や無駄を嫌う、まさに論理の探求者です。", relationships: "恋愛においては、知的な刺激と深い精神的な結びつきを重視します。感情表現は苦手ですが、パートナーの成長を促し、共に未来を築くことに大きな価値を見出します。忠誠心は非常に強いですが、その高い基準についてこられる相手を求めます。", career_paths: ["戦略コンサルタント", "ソフトウェア開発者", "科学者", "大学教授", "弁護士", "エンジニア"], famous_people: ["イーロン・マスク", "フリードリヒ・ニーチェ", "スティーヴン・ホーキング", "アーノルド・シュワルツェネッガー"], cognitive_functions: { dominant: { name: "内向的直観 (Ni)", description: "未来の可能性や物事の背後にあるパターンを、無意識的に、しかし深く洞察します。" }, auxiliary: { name: "外向的思考 (Te)", description: "目標達成のために、外部の世界を論理的に整理し、効率的なシステムを構築します。" }, tertiary: { name: "内向的感情 (Fi)", description: "自身の内なる価値観や感情に基づいて判断しますが、普段はあまり表に出しません。" }, inferior: { name: "外向的感覚 (Se)", description: "ストレス下で、衝動的に感覚的な快楽（過食、衝動買いなど）に走ることがあります。" } }, conversation: `「その計画には3つの構造的欠陥がある。まず第一に、リソース配分が非効率だ。改善案として、AとBのタスクを統合し…」` },
    "INTP": { alias: "論理学者", title: "INTP (論理学者型)", tagline: "知的好奇心を原動力に、世界の謎を探求する発明家", description: "ユニークな視点と旺盛な知的好奇心を持つ、生まれながらの発明家です。世界の根本的な仕組みや宇宙の謎に惹かれ、常に頭の中で様々な理論やアイデアをこねくり回しています。既存のルールよりも、自らが納得できる論理を優先します。", relationships: "恋愛においては、パートナーと知的な議論や共通の趣味を共有できることを楽しみます。感情的なドラマや束縛を嫌い、お互いの独立した時間を尊重する関係を好みます。愛情表現は不器用ですが、相手のアイデアや思考を理解しようと努めることで愛を示します。", career_paths: ["哲学者", "システムアナリスト", "研究開発", "データサイエンティスト", "プログラマー", "経済学者"], famous_people: ["アルバート・アインシュタイン", "ビル・ゲイツ", "アイザック・ニュートン", "クリステン・スチュワート"], cognitive_functions: { dominant: { name: "内向的思考 (Ti)", description: "物事の仕組みを正確に理解するため、内部に一貫した論理体系を構築します。" }, auxiliary: { name: "外向的直観 (Ne)", description: "様々な可能性やアイデアを外部の世界から見つけ出し、それらを自らの論理体系と結びつけます。" }, tertiary: { name: "内向的感覚 (Si)", description: "過去の経験や詳細なデータを参照しますが、新しいアイデアを優先するあまり見過ごしがちです。" }, inferior: { name: "外向的感情 (Fe)", description: "ストレス下で、普段は気にしない他人の評価を過剰に気にしたり、感情的になったりします。" } }, conversation: `「面白い。君の意見は僕の仮説とは異なるが、その前提となる論理的根拠を説明してもらえるかい？」` },
    "ENTJ": { alias: "指揮官", title: "ENTJ (指揮官型)", tagline: "大胆な想像力と強い意志で、道を切り拓くリーダー", description: "大胆で想像力豊か、そして強い意志を持つ天性のリーダーです。課題を見つけると、その解決策を創造し、人々を率いて目標を達成することに大きな喜びを感じます。非効率を許さず、常に挑戦と成長を求めます。", relationships: "恋愛においても主導権を握り、パートナーと共に成長し、目標を達成していく関係を望みます。甘い言葉よりも、具体的な行動や計画で愛情を示します。自分と同じように野心的で、知的な会話ができるパートナーに強く惹かれます。", career_paths: ["経営者(CEO)", "プロジェクトマネージャー", "政治家", "起業家", "マネジメントコンサルタント", "弁護士"], famous_people: ["スティーブ・ジョブズ", "マーガレット・サッチャー", "ナポレオン・ボナパルト", "ゴードン・ラムゼイ"], cognitive_functions: { dominant: { name: "外向的思考 (Te)", description: "目標達成のために、外部の世界を論理的に整理し、効率的なシステムを構築します。" }, auxiliary: { name: "内向的直観 (Ni)", description: "未来の可能性や物事の背後にあるパターンを洞察し、それを自らの計画に活かします。" }, tertiary: { name: "外向的感覚 (Se)", description: "現在の状況や物理的な現実を把握し、行動に移す力を持っています。" }, inferior: { name: "内向的感情 (Fi)", description: "ストレス下で、自分の感情や価値観に自信が持てなくなり、過度に感傷的になることがあります。" } }, conversation: `「よし、目標は明確だ。君はAを、僕はBを担当する。3日後に進捗を確認しよう。何か問題があれば、すぐに報告してくれ。」` },
    "ENTP": { alias: "討論者", title: "ENTP (討論者型)", tagline: "知的な挑戦を愛し、現状に疑問を投げかける思考家", description: "頭の回転が速く、好奇心旺盛な『悪魔の代弁者』。あらゆるアイデアや意見に対して、その弱点を見つけ出し、知的な討論を仕掛けることを楽しみます。常識や伝統に縛られず、常に新しい可能性を探求しています。", relationships: "恋愛においては、機知に富んだ会話と、予測不可能な刺激を楽しみます。パートナーが自分のアイデアに乗り、一緒に物事を分析したり、新しいことに挑戦したりすることを望みます。束縛を嫌い、自由な関係を好みますが、知的に対等な相手には強い魅力を感じます。", career_paths: ["発明家", "マーケティング戦略家", "放送ジャーナリスト", "広告クリエイター", "政治アナリスト", "俳優"], famous_people: ["レオナルド・ダ・ヴィンチ", "トム・ハンクス", "ソクラテス", "セリーヌ・ディオン"], cognitive_functions: { dominant: { name: "外向的直観 (Ne)", description: "様々な可能性やアイデアを外部の世界から見つけ出し、それらを素早く結びつけます。" }, auxiliary: { name: "内向的思考 (Ti)", description: "見つけ出したアイデアが論理的に一貫しているか、内部の論理体系で厳密に検証します。" }, tertiary: { name: "外向的感情 (Fe)", description: "他人を魅了し、自分のアイデアに巻き込むために、社交的なスキルを使います。" }, inferior: { name: "内向的感覚 (Si)", description: "ストレス下で、普段は無視するような細かい事実や過去の出来事にとらわれてしまいます。" } }, conversation: `「君は『Aは正しい』と言うけれど、もし逆の視点から見たらどうだろう？例えば、Bという前提を置いた場合、その理論は完全に崩壊しないかい？」` },
    "INFJ": { alias: "提唱者", title: "INFJ (提唱者型)", tagline: "静かな理想を胸に、世界をより良くしようと努める人", description: "物静かで神秘的ですが、その内側には揺るぎない信念と理想主義が燃えています。単に夢を見るだけでなく、具体的な行動で世界をより良い場所に変えようとします。深い洞察力で人の本質を見抜く力があります。", relationships: "恋愛においては、表面的ではない、魂と魂が触れ合うような深い結びつきを求めます。理想が高く、パートナー選びには非常に慎重。一度信頼した相手には、深い愛情と献身を注ぎますが、自分の複雑な内面を理解してもらえないと深く傷つきます。", career_paths: ["臨床心理士", "組織開発コンサルタント", "人権活動家", "教師", "ライター", "ソーシャルワーカー"], famous_people: ["マーティン・ルーサー・キング・ジュニア", "ネルソン・マンデラ", "マザー・テレサ", "テイラー・スウィフト"], cognitive_functions: { dominant: { name: "内向的直観 (Ni)", description: "未来の可能性や物事の背後にあるパターンを、無意識的に、しかし深く洞察します。" }, auxiliary: { name: "外向的感情 (Fe)", description: "周りの人々の感情やニーズを敏感に察知し、調和のとれた環境を作ろうとします。" }, tertiary: { name: "内向的思考 (Ti)", description: "自分の洞察や判断が論理的に正しいか、内的に検証します。" }, inferior: { name: "外向的感覚 (Se)", description: "ストレス下で、衝動的に感覚的な快楽に走ったり、細部に過剰にこだわったりします。" } }, conversation: `「人々が本当の意味で互いを理解し合える世界を作るには、まず私たち一人ひとりが、自分の中にある偏見に気づくことから始めなければならないと思うんだ。」` },
    "INFP": { alias: "仲介者", title: "INFP (仲介者型)", tagline: "静かな情熱を燃やす、心優しき理想主義者", description: "詩人肌で、常に物事の善い面を探し求める真の理想主義者。自分の内なる価値観や信念に深く根ざしており、その独自の視点から世界を眺めます。非常に共感力が高く、他人の感情を自分のことのように感じ取ることができます。", relationships: "恋愛においては、理想的なパートナーシップと深い精神的な繋がりを求めます。表面的な関係には興味がなく、魂レベルでの理解者を求めています。一度心を開いた相手には非常に献身的ですが、自分の感情を言葉にするのが苦手なため、パートナーはINFPの心の機微を察する努力が必要です。", career_paths: ["作家", "カウンセラー", "アーティスト", "グラフィックデザイナー", "NPO職員", "心理学者"], famous_people: ["シェイクスピア", "J.R.R. トールキン", "ジョニー・デップ", "オードリー・ヘプバーン"], cognitive_functions: { dominant: { name: "内向的感情 (Fi)", description: "自分の価値観や感情を深く探求し、それが行動の基盤となります。" }, auxiliary: { name: "外向的直観 (Ne)", description: "様々な可能性やアイデアを外部の世界から見つけ出します。" }, tertiary: { name: "内向的感覚 (Si)", description: "過去の経験や詳細な情報を記憶し、現在の状況と比較します。" }, inferior: { name: "外向的思考 (Te)", description: "ストレス時に現れ、非効率な状況に批判的になります。" } }, conversation: `友人: 「最近、何だかやる気が出なくて…」\nINFP: 「そっか…。無理しないでいいんだよ。時には立ち止まることも大切だと思う。あなたが本当に心から『やりたい』って思えることが見つかるまで、ゆっくり探してもいいんじゃないかな。」` },
    "ENFJ": { alias: "主人公", title: "ENFJ (主人公型)", tagline: "カリスマ性と情熱で、人々をより良い未来へ導くリーダー", description: "人々を惹きつける天性のカリスマと、溢れる情熱を持っています。他人の感情や動機に敏感で、その人の可能性を最大限に引き出すことに喜びを感じます。周りの人々を巻き込み、共通の目標に向かって導く、まさに物語の主人公です。", relationships: "恋愛においては、パートナーの成長をサポートし、共に理想的な関係を築くことに情熱を注ぎます。愛情深く、献身的ですが、時に相手に期待しすぎたり、おせっかいになったりすることも。オープンなコミュニケーションと感謝の言葉を大切にします。", career_paths: ["教師", "人事マネージャー", "広報担当", "非営利団体のディレクター", "政治家", "ライフコーチ"], famous_people: ["バラク・オバマ", "オプラ・ウィンフリー", "マーティン・フリーマン", "ジェニファー・ローレンス"], cognitive_functions: { dominant: { name: "外向的感情 (Fe)", description: "周りの人々の感情やニーズを敏感に察知し、調和のとれた環境を作ろうとします。" }, auxiliary: { name: "内向的直観 (Ni)", description: "未来の可能性や人々の成長の道筋を、長期的な視点で洞察します。" }, tertiary: { name: "外向的感覚 (Se)", description: "現在の状況や物理的な現実を把握し、人々を楽しませるために行動します。" }, inferior: { name: "内向的思考 (Ti)", description: "ストレス下で、過度に自己批判的になったり、他人の行動の論理性を厳しく問い詰めたりします。" } }, conversation: `「君なら絶対にできると信じてるよ。何か困ったことがあったら、いつでも僕を頼ってくれ。君の成功は、僕にとっても最高の喜びなんだ。」` },
    "ENFP": { alias: "広報運動家", title: "ENFP (広報運動家型)", tagline: "情熱的な創造力で人々を魅了する、自由な精神の持ち主", description: "自由な精神の持ち主で、常に大きなアイデアや可能性に夢中になっています。カリスマ性と豊かな感情表現で、人々との間に強いつながりを築きます。ルーチンワークよりも、新しい挑戦や創造的なプロジェクトに情熱を燃やします。", relationships: "恋愛においては、情熱的でロマンチックな関係を求めます。パートナーとの間に深い精神的な結びつきと、刺激的な対話があることを重視します。自由を愛するため、束縛されることを嫌いますが、一度心を決めると非常に忠実なパートナーになります。", career_paths: ["コピーライター", "ジャーナリスト", "俳優", "人事担当", "起業家", "コンサルタント"], famous_people: ["ロビン・ウィリアムズ", "クエンティン・タランティーノ", "サンドラ・ブロック", "ウィル・スミス"], cognitive_functions: { dominant: { name: "外向的直観 (Ne)", description: "様々な可能性やアイデアを外部の世界から見つけ出し、それらを素早く結びつけます。" }, auxiliary: { name: "内向的感情 (Fi)", description: "見つけ出したアイデアが、自分の内なる価値観と一致しているかを判断します。" }, tertiary: { name: "外向的思考 (Te)", description: "アイデアを実現するために、論理的に計画を立て、実行しようとします。" }, inferior: { name: "内向的感覚 (Si)", description: "ストレス時に、過去の失敗にとらわれたり、細部にこだわりすぎたりします。" } }, conversation: `ENFP: 「ねえ、すごいこと思いついちゃった！もし、僕たちが空飛ぶ車を作ったら、世界は絶対変わると思わない！？資金集めはどうする？設計は？考えるだけでワクワクするよ！」` },
    "ISTJ": { alias: "管理者", title: "ISTJ (管理者型)", tagline: "事実と論理を重んじ、社会の安定を支える実務家", description: "実用的で事実に忠実な、頼れる現実主義者。その行動は常に論理と責任感に裏打ちされています。伝統やルールを尊重し、与えられた仕事はどんなことであれ最後までやり遂げる、組織に不可欠な存在です。", relationships: "恋愛においては、安定と信頼を最も重視します。派手な愛情表現はしませんが、日々の行動や責任を果たすことで、深く、揺るぎない愛情を示します。伝統的な家庭観を持つことが多く、誠実で責任感のあるパートナーを求めます。", career_paths: ["会計士", "公務員", "システム管理者", "監査役", "物流マネージャー", "警察官"], famous_people: ["ジョージ・ワシントン", "アンゲラ・メルケル", "デンゼル・ワシントン", "ナタリー・ポートマン"], cognitive_functions: { dominant: { name: "内向的感覚 (Si)", description: "過去の経験や詳細なデータを正確に記憶し、それを現在の判断基準とします。" }, auxiliary: { name: "外向的思考 (Te)", description: "目標達成のために、事実に基づいて外部の世界を論理的に整理し、計画を実行します。" }, tertiary: { name: "内向的感情 (Fi)", description: "自身の価値観を持っていますが、義務や論理を優先するため、あまり表に出しません。" }, inferior: { name: "外向的直観 (Ne)", description: "ストレス下で、未来に対して悲観的になったり、ありえないような悪い可能性を想像してしまいます。" } }, conversation: `「この手順書によれば、次の工程はB-3のはずだ。規定通りに進めよう。」` },
    "ISFJ": { alias: "擁護者", title: "ISFJ (擁護者型)", tagline: "献身的な優しさで、大切な人々を守る縁の下の力持ち", description: "非常に献身的で、思いやりにあふれる、心優しき守護者。大切な人々を助け、支えることに大きな喜びを感じます。控えめですが観察眼に優れ、周りの人が何を必要としているかを敏感に察知します。", relationships: "恋愛においては、パートナーに尽くし、家庭的な温かい関係を築くことを望みます。相手の記念日や好きなものを決して忘れず、細やかな気配りで愛情を表現します。安定と調和を何よりも大切にする、忠実なパートナーです。", career_paths: ["看護師", "保育士", "秘書", "図書館司書", "人事担当", "インテリアデコレーター"], famous_people: ["ビヨンセ", "アン・ハサウェイ", "ヴィン・ディーゼル", "エリザベス女王2世"], cognitive_functions: { dominant: { name: "内向的感覚 (Si)", description: "過去の経験や人々の詳細な情報を正確に記憶し、それを現在の判断基準とします。" }, auxiliary: { name: "外向的感情 (Fe)", description: "周りの人々の感情やニーズを敏感に察知し、調和を保つために行動します。" }, tertiary: { name: "内向的思考 (Ti)", description: "事実やデータに基づいて、物事を論理的に分析しようとします。" }, inferior: { name: "外向的直観 (Ne)", description: "ストレス下で、未来に対して過剰な心配をしたり、ネガティブな可能性ばかりを考えてしまいます。" } }, conversation: `「あなた、最近疲れているみたいだから、好きなケーキ買ってきたよ。無理しないでね。」` },
    "ESTJ": { alias: "幹部", title: "ESTJ (幹部型)", tagline: "秩序と伝統を重んじ、人々を導く優れた管理者", description: "物事を組織し、管理することに長けた、生まれながらのリーダー。伝統や秩序を重んじ、何が正しく、何が間違っているかという明確な信念を持っています。人々をまとめ、コミュニティを正しい方向へ導くことに誇りを感じます。", relationships: "恋愛においては、安定した信頼できる関係を求めます。パートナーや家族に対する責任感が非常に強く、社会的な義務を果たすことで愛情を示します。率直で正直なコミュニケーションを好み、献身的で頼りになるパートナーです。", career_paths: ["経営幹部", "裁判官", "財務アドバイザー", "軍の将校", "不動産業者", "コーチ"], famous_people: ["サミュエル・L・ジャクソン", "ウーマ・サーマン", "ジュディ・シンドリン", "ジョン・D・ロックフェラー"], cognitive_functions: { dominant: { name: "外向的思考 (Te)", description: "目標達成のために、外部の世界を論理的に整理し、効率的なシステムを構築します。" }, auxiliary: { name: "内向的感覚 (Si)", description: "過去の成功例や確立された手順を参考にし、安定した運営を目指します。" }, tertiary: { name: "外向的直観 (Ne)", description: "新しい可能性やアイデアを認識しますが、実績のある方法を優先する傾向があります。" }, inferior: { name: "内向的感情 (Fi)", description: "ストレス下で、自分の感情をコントロールできなくなったり、他人の批判に過敏に反応したりします。" } }, conversation: `「このプロジェクトを成功させるための最適解は、実績のあるこの手法だ。皆、私の指示に従ってくれれば問題ない。」` },
    "ESFJ": { alias: "領事官", title: "ESFJ (領事官型)", tagline: "思いやりと社交性で、人々を繋ぎ、コミュニティを育む人", description: "非常に社交的で、常に人々を気遣う、人気者の世話役。周りの人々が幸せで、調和が保たれていることに喜びを感じます。地域のイベントやパーティーを企画するのが得意で、人々を繋ぐ中心的な存在です。", relationships: "恋愛においては、パートナーとの調和と安定を非常に大切にします。愛情深く、相手の誕生日や記念日を盛大に祝うことを楽しみます。パートナーからの感謝や肯定的なフィードバックを強く求め、社会的に認められるような関係を望む傾向があります。", career_paths: ["ソーシャルワーカー", "営業担当", "企業の受付", "イベントコーディネーター", "小学校教師", "看護師"], famous_people: ["テイラー・スウィフト", "ビル・クリントン", "ジェニファー・ロペス", "ダニー・グローヴァー"], cognitive_functions: { dominant: { name: "外向的感情 (Fe)", description: "周りの人々の感情やニーズを敏感に察知し、調和のとれた環境を作ろうとします。" }, auxiliary: { name: "内向的感覚 (Si)", description: "過去の経験や社会的な慣習を重んじ、それを現在の行動の指針とします。" }, tertiary: { name: "外向的直観 (Ne)", description: "新しい可能性や人々の未来について考えますが、安定を優先するため大きな変化は好みません。" }, inferior: { name: "内向的思考 (Ti)", description: "ストレス下で、他人の行動を過度に論理的に分析し、批判的になってしまうことがあります。" } }, conversation: `「今度の週末、みんなでバーベキューしない？私が場所の予約から買い出しまで、全部準備しておくから！」` },
    "ISTP": { alias: "巨匠", title: "ISTP (巨匠型)", tagline: "大胆かつ実践的な思考で、あらゆるものを探求し作り出す人", description: "冷静な合理性と旺盛な好奇心を持つ、実践的な問題解決者。物事の仕組みを理解し、手を使って何かを作り出したり、修理したりすることに長けています。理論よりも実践を重んじ、危機的状況でも冷静さを失いません。", relationships: "恋愛においては、パートナーと共通の活動や趣味を楽しむ、自由で対等な関係を好みます。言葉での愛情表現は少ないですが、相手のために何かを修理したり、問題を解決したりすることで愛を示します。束縛を嫌い、お互いのプライベートな空間を尊重します。", career_paths: ["メカニック", "パイロット", "消防士", "ソフトウェアエンジニア", "フォレンジック科学者", "大工"], famous_people: ["クリント・イーストウッド", "トム・クルーズ", "スカーレット・ヨハンソン", "ブルース・リー"], cognitive_functions: { dominant: { name: "内向的思考 (Ti)", description: "物事の仕組みを正確に理解するため、内部に一貫した論理体系を構築します。" }, auxiliary: { name: "外向的感覚 (Se)", description: "五感を通して現在の環境を鮮やかに体験し、物理的な世界に即座に対応します。" }, tertiary: { name: "内向的直観 (Ni)", description: "物事の長期的なパターンや可能性をぼんやりと捉えますが、あまり重視しません。" }, inferior: { name: "外向的感情 (Fe)", description: "ストレス下で、普段は抑えている感情が爆発したり、他人の感情に不器用に対応したりします。" } }, conversation: `「このエンジン音は異常だ。おそらく点火プラグの問題だろう。ちょっと分解して確認してみる。」` },
    "ISFP": { alias: "冒険家", title: "ISFP (冒険家型)", tagline: "自由な心で世界を描く、控えめなアーティスト", description: "常に新しいことに挑戦する準備ができている、柔軟で魅力的な芸術家。控えめで物静かな印象ですが、その内面には熱い情熱と好奇心を秘めています。五感を通して世界を体験し、その美しさを自分なりの方法で表現することに喜びを感じます。", relationships: "恋愛においては、パートナーとの間に穏やかで調和のとれた関係を築きたいと願います。言葉よりも行動で愛情を示すタイプ。束縛を嫌い、お互いの自由な時間を尊重することを大切にします。感受性が豊かで傷つきやすいため、思いやりのある優しいコミュニケーションが不可欠です。 ", career_paths: ["ミュージシャン", "シェフ", "獣医師", "写真家", "花屋", "インテリアデザイナー"], famous_people: ["マイケル・ジャクソン", "レディー・ガガ", "ブラッド・ピット", "ボブ・マーリー"], cognitive_functions: { dominant: { name: "内向的感情 (Fi)", description: "自分の価値観や感情を深く探求し、それが行動の基盤となります。" }, auxiliary: { name: "外向的感覚 (Se)", description: "五感を通して現在の環境を鮮やかに体験し、即興で行動します。" }, tertiary: { name: "内向的直観 (Ni)", description: "物事の長期的なパターンや可能性をぼんやりと捉えます。" }, inferior: { name: "外向的思考 (Te)", description: "ストレス下では、非効率さにイライラしたり、他人に批判的になったりします。" } }, conversation: `（公園のベンチで）\n友人: 「何してるの？」\nISFP: 「…うん、別に。ただ、風の音とか、葉っぱが揺れるのを見てるだけ。なんだか心地よくて。こういう時間、好きだなあって。」` },
    "ESTP": { alias: "起業家", title: "ESTP (起業家型)", tagline: "賢く、エネルギッシュで、リスクを恐れない行動派", description: "常にエネルギッシュで、今この瞬間のスリルを追い求める行動派。人々の注目を集めるのが得意で、その場の状況を即座に判断し、リスクを恐れずに行動に移します。退屈を嫌い、常に刺激的な環境に身を置くことを好みます。", relationships: "恋愛においては、情熱的でスリリングな関係を楽しみます。パートナーと一緒にアクティブなデートをしたり、サプライズを仕掛けたりするのが好きです。束縛されることを嫌い、自由な関係を望みますが、自分についてこれる度胸のある相手に強く惹かれます。", career_paths: ["起業家", "救急救命士", "セールスディレクター", "探偵", "プロスポーツ選手", "金融トレーダー"], famous_people: ["ドナルド・トランプ", "マドンナ", "エディ・マーフィ", "ジャック・ニコルソン"], cognitive_functions: { dominant: { name: "外向的感覚 (Se)", description: "五感を通して現在の環境を鮮やかに体験し、物理的な世界に即座に対応します。" }, auxiliary: { name: "内向的思考 (Ti)", description: "状況を素早く論理的に分析し、最も効果的な行動を選択します。" }, tertiary: { name: "外向的感情 (Fe)", description: "他人を魅了し、自分のペースに巻き込むために、社交的なスキルを使います。" }, inferior: { name: "内向的直観 (Ni)", description: "ストレス下で、将来に対して根拠のない不安を感じたり、他人の裏を考えすぎてしまいます。" } }, conversation: `「議論している暇があったら、まずやってみようぜ。失敗したらその時考えればいい。このスリルがたまらないんだよ！」` },
    "ESFP": { alias: "エンターテイナー", title: "ESFP (エンターテイナー型)", tagline: "今この瞬間を輝かせる、天性のパフォーマー", description: "自発的でエネルギッシュ、そして熱意にあふれる、まさに天性のエンターテイナー。『今、この瞬間』を最大限に楽しむことを愛し、その喜びを周りの人々と分かち合うことに生きがいを感じます。美的センスに優れ、人々の注目を浴びるのが大好きです。", relationships: "恋愛においては、刺激的で楽しい関係を好みます。パートナーと一緒に新しい体験をしたり、イベントに参加したりすることを楽しむでしょう。愛情表現はストレートで情熱的。しかし、退屈や対立を嫌うため、真剣な問題から目をそらしてしまう傾向もあります。", career_paths: ["俳優", "イベントプランナー", "ツアーガイド", "ファッションデザイナー", "セールス担当", "美容師"], famous_people: ["マリリン・モンロー", "レオナルド・ディカプリオ", "アデル", "ジェイミー・オリヴァー"], cognitive_functions: { dominant: { name: "外向的感覚 (Se)", description: "五感を通して現在の環境を鮮やかに体験し、即興で行動します。" }, auxiliary: { name: "内向的感情 (Fi)", description: "自分の内なる価値観に基づいて判断し、他人の感情にも敏感です。" }, tertiary: { name: "外向的思考 (Te)", description: "物事を効率的に整理し、論理的に計画を立てようとします。" }, inferior: { name: "内向的直観 (Ni)", description: "ストレス時に、将来に対する漠然とした不安を感じます。" } }, conversation: `（友人との会話）\nESFP: 「もう仕事終わり！お疲れ様！ねえ、この後どうする？駅前に新しいお店できたの知ってる？そこのテラス席が最高らしいよ！今から行けば夕日に間に合うかも！行こうよ、絶対楽しいって！」` },
};

// 【プレミアム分析】主要な組み合わせの詳細データ
const compatibilityData = {
    // ▼▼▼ ご要望の組み合わせを追加 ▼▼▼
    "ENFJ-ENTJ": { compatibility_level: "強力なパワーカップル", title: "ENFJとENTJの相性", relationship_summary: "共に外向的(E)、直観的(N)、判断(J)型であり、社会に影響を与えたいという強い意志を共有する、まさにパワーカップル。ENTJが論理的な戦略と効率性で「何をすべきか」を示し、ENFJが共感力とカリスマ性で「どのように人々を巻き込むか」を担います。二人が組めば、どんな大きな目標でも達成できるでしょう。", strengths_in_relationship: ["<strong>目標達成能力:</strong> 二人の強みを合わせれば、公私ともに大きな成功を収めることができる。","<strong>相互の尊敬:</strong> 互いの能力と野心を深く尊敬し、高め合うことができる。","<strong>安定した関係:</strong> J型同士であるため、計画的に関係を築き、将来に対するビジョンを共有できる。"], potential_challenges: ["<strong>感情(F) vs 論理(T)の衝突:</strong> ENFJが人間関係や調和を優先するのに対し、ENTJは効率と結果を優先するため、意見が対立することがある。","<strong>主導権争い:</strong> どちらもリーダーシップを発揮するタイプなため、家庭内や共同プロジェクトで主導権を争う可能性がある。","<strong>燃え尽き症候群:</strong> 常に高い目標を追い求めるため、二人ともリラックスする時間を見失い、心身ともに疲弊してしまうことがある。"], advice_for_couple: ["意思決定の際は、ENTJの「論理的な正しさ」とENFJの「感情的な影響」の両方を考慮に入れるルールを作りましょう。","意識的に「何もしない時間」や「仕事の話をしないデート」を設け、心からリラックスする習慣をつけましょう。","お互いのリーダーシップを認め、家庭、仕事など、場面ごとに得意な方が主導権を握るように役割分担するとうまくいきます。"], conversation: `ENTJ: 「来年の資産目標達成のため、この投資戦略が最も効率的だと分析した。今すぐ実行すべきだ。」\nENFJ: 「計画は素晴らしいわ。でも、それを実行することでチームのAさんがどう感じるか、少し考えてみない？彼女の協力を得られれば、もっとスムーズに進むはずよ。」\nENTJ: 「…なるほど。人的要因か。君の意見も取り入れて、計画を修正しよう。ありがとう。」` },
    "ENFP-INFJ": { compatibility_level: "理想的な関係 (魂のパートナー)", title: "ENFPとINFJの相性", relationship_summary: "直観(N)と感情(F)を共有し、互いの内面世界に深く惹かれ合う、まさにソウルメイトと呼べる関係。ENFPがもたらす無限の可能性と明るさが、INFJの秘めたる理想の世界に光を当てます。INFJの深い洞察力は、ENFPの奔放なエネルギーに羅針盤を与え、二人の関係は常に成長と発見に満ちています。", strengths_in_relationship: ["<strong>深い精神的結びつき:</strong> 表面的な会話を超え、互いの価値観や夢について語り合える。","<strong>相互補完:</strong> ENFPの社交性がINFJを外の世界に導き、INFJの計画性がENFPのアイデアを形にするのを助ける。","<strong>肯定的な関係:</strong> 互いの個性や可能性を心から信じ、肯定し合うことができる。"], potential_challenges: ["<strong>エネルギーレベルの違い:</strong> 外向的なENFPと内向的なINFJでは、求める社交の頻度や休息の仕方が異なる。","<strong>理想と現実の衝突:</strong> 共に理想主義的なため、現実的な問題（お金、家事など）の処理が後回しになりがち。","<strong>すれ違い:</strong> INFJは内に秘めるタイプ、ENFPはオープンなタイプなため、INFJが黙って傷ついていることにENFPが気づかないことがある。"], advice_for_couple: ["「一人の時間」と「二人の時間」のスケジュールを共有し、お互いのペースを尊重しましょう。","INFJは自分の気持ちや境界線を、穏やかに、しかし明確に言葉で伝える努力をしましょう。","月に一度、家計や将来の計画など、現実的なテーマについて話し合う「作戦会議」を開くのがおすすめです。"], conversation: `ENFP: 「聞いて！世界中の子供たちが無料で学べるオンラインスクールを作るってアイデア、どう思う！？」\nINFJ: 「素晴らしいアイデアだね。その学校の理念は『競争』ではなく『共感』に根差したものであるべきだと思う。君の情熱があれば、きっと実現できるよ。」` },
    // ▼以前のデータも最高品質のフォーマットに統一・拡充▼
    "ESFP-INFP": { compatibility_level: "魅力的で成長できる関係 (互いの世界を広げる)", title: "ESFPとINFPの相性", relationship_summary: "『今を楽しむ現実主義者』ESFPと、『未来を夢見る理想主義者』INFP。一見正反対ですが、共に感情(F)を大切にし、柔軟(P)であるという強い共通軸があります。ESFPはINFPを内なる世界から現実の楽しさへと誘い、INFPはESFPに日常の裏にある意味や感動を与えます。互いの違いを好奇心を持って受け入れれば、これ以上ないほど視野を広げ、共に成長できる刺激的な関係です。", strengths_in_relationship: ["<strong>相互補完:</strong> ESFPの行動力がINFPのアイデアを形にし、INFPの深い洞察がESFPの行動に意味を与える。","<strong>感情的な共鳴:</strong> 共に感情(F)を重視するため、相手の気持ちを尊重し、温かい関係を築ける。","<strong>柔軟な関係:</strong> 計画に縛られないP型同士なので、その場の流れを楽しむ自由な付き合い方ができる。"], potential_challenges: ["<strong>エネルギーレベルの違い:</strong> 外向的なESFPと内向的なINFPでは、求める刺激の量や休息の取り方が異なる。","<strong>現実と理想のギャップ:</strong> ESFPの現実主義とINFPの理想主義が、お金の使い方や将来設計で衝突する可能性がある。","<strong>コミュニケーションの壁:</strong> 感じたことをすぐ口にするESFPと、じっくり考えてから話すINFPとの間で、会話のテンポが合わないことがある。"], advice_for_couple: ["お互いの『エネルギー残量』を尊重し、一人の時間と二人の時間のバランスを大切にしましょう。","ESFPはINFPの空想的な話を否定せず「面白いね！」と受け入れ、INFPはESFPの現実的な提案に「やってみよう！」と乗ってみましょう。","大きな決断をする際は、INFPの「理想」とESFPの「現実的な手段」を組み合わせることを意識するとうまくいきます。"], conversation: `ESFP: 「このライブ最高！理屈抜きで楽しい！一緒に最前列まで行ってもみくちゃになろうよ！」\nINFP: 「うん、すごい熱気だね！この一体感、まるで巨大な一つの生き物みたい。この瞬間を詩にしたら、どんな言葉になるだろう…。」\nESFP: 「詩！いいね！じゃあ、この最高の気分を君が詩にして、僕がそれに曲をつけちゃうってのはどう！？」` },
    "ENFP-ESFP": { compatibility_level: "非常に良好 (最高の遊び仲間)", title: "ENFPとESFPの相性", relationship_summary: "共に外向的(E)、感情的(F)、柔軟(P)であり、人生をとことん楽しみたいという点で固く結ばれた、最強のエンタメコンビです。ENFPが提供する『突飛なアイデア』を、ESFPが『現実での楽しみ方』に変換することで、二人の周りには常に笑いと刺激が絶えません。", strengths_in_relationship: ["<strong>無限の楽しさ:</strong> 新しいことへの好奇心が尽きず、二人でいれば退屈することはない。","<strong>ポジティブなエネルギー:</strong> 互いに励まし合い、ポジティブな雰囲気を生み出すのが得意。","<strong>感情的なオープンさ:</strong> 共に自分の気持ちを素直に表現するため、風通しの良い関係を築ける。"], potential_challenges: ["<strong>現実逃避:</strong> 楽しさを追求するあまり、地道な作業や面倒な問題から目をそらしがち。","<strong>計画性のなさ:</strong> 二人とも計画(J)が苦手なため、約束が曖昧になったり、重要なことを見落としたりする可能性がある。","<strong>深い話の不足:</strong> ENFPが時折求める哲学的な対話を、現実主義のESFPが「難しくて退屈」と感じてしまうことがある。"], advice_for_couple: ["カレンダーアプリを共有し、重要な予定やタスクは二人で確認する習慣をつけましょう。","ESFPはENFPの夢見がちな話を「面白いSF映画みたいだね」と楽しみ、ENFPはESFPの現実的な楽しみに全力で乗ってみましょう。","月に一度、静かな場所で「最近、本当に考えてること」についてゆっくり話す時間を持つのも良いでしょう。"], conversation: `ENFP: 「ねえ、無人島を買って国作らない！？」\nESFP: 「国！いいね！じゃあまず、国旗のデザイン考えよう！絶対オシャレなやつ！で、国民食はタコスね！今からタコス食べに行かない？」\nENFP: 「最高！食べながら国名を考えよう！その勢い、大好きだよ！」` },
    "ESFP-ISFP": { compatibility_level: "非常に良好 (心地よいアーティスト仲間)", title: "ESFPとISFPの相性", relationship_summary: "エネルギーの方向性(E/I)こそ違えど、世界の感じ方(S)、価値観(F)、ライフスタイル(P)が全く同じであるため、まるで波長の合う双子のような関係です。多くを語らずとも互いを理解し、リラックスした時間を共有できます。", strengths_in_relationship: ["<strong>共通の美的感覚:</strong> 美しいものや楽しい体験を共に心から楽しめる。", "<strong>心地よいペース感:</strong> ESFPがリードし、ISFPが自然にそれに応じる形で無理のない関係が築ける。", "<strong>感情的なサポート:</strong> 互いに気持ちに寄り添い、サポートし合える。"], potential_challenges: ["<strong>問題の先送り:</strong> 現在の楽しさを優先し、対立を避けるため、重要な問題から目をそらしがち。", "<strong>計画性の欠如:</strong> 長期的な計画や将来設計が苦手なため、現実的なタスクが滞る可能性がある。", "<strong>感情表現のすれ違い:</strong> オープンなESFPと、内に秘めるISFPとの間で誤解が生じることがある。"], advice_for_couple: ["定期的に将来の話をする日を設ける", "一人の時間を尊重する", "小さなことでも気持ちを言葉で伝える"], conversation: `ESFP: 「見て、この服すごく可愛くない！？絶対似合うよ、試着してみなよ！」\nISFP: 「本当だ、素敵なデザインだね。うん、ちょっと着てみようかな。（静かに微笑む）」` }
};

// --- 以下、ロジック部分は変更ありません ---
const inputEl = document.getElementById('mbti-input');
const analyzeBtn = document.getElementById('analyze-button');
const resultArea = document.getElementById('result-area');
analyzeBtn.addEventListener('click', analyzeMbti);
inputEl.addEventListener('keyup', (event) => { if (event.key === 'Enter') analyzeMbti(); });
function analyzeMbti() {
    const inputText = inputEl.value.trim().toUpperCase();
    if (!inputText) { resultArea.innerHTML = `<p class="result-card">分析したいMBTIタイプを入力してください。</p>`; return; }
    const types = inputText.split(/[\s,]+/).filter(type => type !== "");
    if (types.length === 1) { displaySingleTypeResult(types[0]); }
    else if (types.length === 2) { displayCompatibilityResult(types[0], types[1]); }
    else { resultArea.innerHTML = `<p class="result-card">エラー: 1つまたは2つのMBTIタイプを正しく入力してください。</p>`; }
}
function displaySingleTypeResult(type) {
    const data = mbtiData[type];
    if (data && data.description !== "データ準備中...") {
        let html = `<div class="result-card single-type"><div class="card-header"><h2>${data.title} - "${data.alias}"</h2><p class="tagline">${data.tagline}</p></div><div class="card-section"><h3><i class="fas fa-user-circle"></i> どんな性格？</h3><p>${data.description}</p></div><div class="card-section"><h3><i class="fas fa-heart"></i> 恋愛・人間関係の傾向</h3><p>${data.relationships}</p></div><div class="card-section grid-2"><div><h3><i class="fas fa-briefcase"></i> 適職の例</h3><ul class="list-pills">${data.career_paths.map(item => `<li>${item}</li>`).join('')}</ul></div><div><h3><i class="fas fa-star"></i> 有名人の例</h3><ul class="list-pills">${data.famous_people.map(item => `<li>${item}</li>`).join('')}</ul></div></div><div class="card-section"><h3><i class="fas fa-brain"></i> 心の仕組み (認知機能)</h3><div class="cognitive-functions"><div class="function-item"><strong>主機能 (Dominant):</strong> ${data.cognitive_functions.dominant.name} - ${data.cognitive_functions.dominant.description}</div><div class="function-item"><strong>補助機能 (Auxiliary):</strong> ${data.cognitive_functions.auxiliary.name} - ${data.cognitive_functions.auxiliary.description}</div><div class="function-item"><strong>第三機能 (Tertiary):</strong> ${data.cognitive_functions.tertiary.name} - ${data.cognitive_functions.tertiary.description}</div><div class="function-item"><strong>劣等機能 (Inferior):</strong> ${data.cognitive_functions.inferior.name} - ${data.cognitive_functions.inferior.description}</div></div></div><div class="card-section"><h3><i class="fas fa-comments"></i> 日常会話の事例</h3><div class="conversation-box"><p>${data.conversation.replace(/\n/g, '<br>')}</p></div></div></div>`;
        resultArea.innerHTML = html;
    } else if (data) {
        resultArea.innerHTML = `<p class="result-card">「${type}」の詳細データは現在準備中です。基本的な性格は「${data.tagline}」です。</p>`;
    } else {
        resultArea.innerHTML = `<p class="result-card">エラー: 「${type}」というMBTIタイプが見つかりませんでした。綴りを確認してください。</p>`;
    }
}
function displayCompatibilityResult(type1, type2) {
    if (!mbtiData[type1] || !mbtiData[type2]) {
        resultArea.innerHTML = `<p class="result-card">エラー: 入力されたMBTIタイプの一部、または両方が見つかりませんでした。綴りを確認してください。</p>`;
        return;
    }
    const key = [type1, type2].sort().join('-');
    const specificData = compatibilityData[key];
    if (specificData) {
        let html = `<div class="result-card compatibility"><div class="card-header"><h2>${specificData.title}</h2><p class="tagline">${specificData.compatibility_level}</p></div><div class="card-section"><h3><i class="fas fa-file-alt"></i> 関係性の概要</h3><p>${specificData.relationship_summary}</p></div><div class="card-section grid-2"><div><h3><i class="fas fa-thumbs-up"></i> 関係性の強み</h3><ul class="list-bullets">${specificData.strengths_in_relationship.map(item => `<li>${item}</li>`).join('')}</ul></div><div><h3><i class="fas fa-exclamation-triangle"></i> 潜在的な課題</h3><ul class="list-bullets">${specificData.potential_challenges.map(item => `<li>${item}</li>`).join('')}</ul></div></div><div class="card-section"><h3><i class="fas fa-lightbulb"></i> うまくいくためのアドバイス</h3><ul class="list-bullets">${specificData.advice_for_couple.map(item => `<li>${item}</li>`).join('')}</ul></div><div class="card-section"><h3><i class="fas fa-comments"></i> 二人の日常会話</h3><div class="conversation-box"><p>${specificData.conversation.replace(/\n/g, '<br>')}</p></div></div></div>`;
        resultArea.innerHTML = html;
    } else {
        let common = 0;
        if(type1[0] === type2[0]) common++; if(type1[1] === type2[1]) common++; if(type1[2] === type2[2]) common++; if(type1[3] === type2[3]) common++;
        let level, summary;
        if (common === 4) { level = "鏡のような関係"; summary = "自分を見ているかのように理解しやすく、非常に心地よい関係です。しかし、似すぎているため新しい視点が得にくい側面も。"; }
        else if (common === 3) { level = "非常に良好な関係"; summary = "ほとんどの点で波長が合い、一つの違いが良いスパイスになります。互いを自然に補完し合える理想的な組み合わせの一つです。"; }
        else if (common === 2) { level = "バランスの取れた関係"; summary = "半分同じで半分違う、学びの多い関係です。違いを乗り越えることで、互いに大きく成長できる可能性を秘めています。"; }
        else if (common === 1) { level = "挑戦的で成長できる関係"; summary = "多くの点で異なりますが、その違いこそが魅力です。自分にないものを相手から学び、視野を広げることができます。"; }
        else { level = "正反対で刺激的な関係"; summary = "まさに『自分とは正反対のタイプ』。最初は戸惑うことも多いかもしれませんが、互いの存在が新しい世界の扉を開く鍵となります。"; }
        let analysis_points = `<li><strong>エネルギーの方向 (E/I):</strong> ${type1[0] === type2[0] ? '共通' : '相違'}</li><li><strong>情報の捉え方 (S/N):</strong> ${type1[1] === type2[1] ? '共通' : '相違'}</li><li><strong>意思決定の基準 (T/F):</strong> ${type1[2] === type2[2] ? '共通' : '相違'}</li><li><strong>物事の進め方 (J/P):</strong> ${type1[3] === type2[3] ? '共通' : '相違'}</li>`;
        let html = `<div class="result-card compatibility"><div class="card-header"><h2>${type1} と ${type2} の相性 (簡易分析)</h2><p class="tagline">${level}</p></div><div class="card-section"><h3><i class="fas fa-file-alt"></i> 関係性の概要</h3><p>${summary}</p></div><div class="card-section"><h3><i class="fas fa-cogs"></i> 4つの指標の比較</h3><ul class="list-bullets">${analysis_points}</ul></div><div class="card-section"><h3><i class="fas fa-lightbulb"></i> うまくいくためのアドバイス</h3><p>お互いの違いは、対立の原因ではなく、学びの機会です。相手が自分と違う方法で世界を見ていることを理解し、「なぜそう考えるんだろう？」と好奇心をもって対話してみましょう。自分にない視点を尊重することが、関係を深める鍵となります。</p></div></div>`;
        resultArea.innerHTML = html;
    }
}